version: "2"

engines:
  markdownlint:
    enabled: true
  pep8:
    enabled: true
  shellcheck:
    enabled: true

ratings:
  paths:
  - "**.py"
  - "**.sh"
  - "**.md"

checks:
  argument-count:
    config:
      threshold: 5
  file-lines:
    config:
      threshold: 1000
  method-count:
    config:
      threshold: 30
  method-lines:
    config:
      threshold: 50
