version: "2"

# engines:
#   pep8:
#     enabled: true
#   shellcheck:
#     enabled: true
#   sonar-python:
#     enabled: true
  # fixme:
  #   enabled: true
  # TODO: https://docs.codeclimate.com/docs/radon
  # radon:
  #   enabled: true
  # TODO: https://docs.codeclimate.com/docs/bandit
  # bandit:
  #   enabled: true

ratings:
  paths:
  - "**.py"
  - "**.sh"


checks:
  argument-count:
    config:
      threshold: 8
  complex-logic:
    config:
      threshold: 40
  file-lines:
    config:
      threshold: 1000
  method-complexity:
    config:
      threshold: 30
  method-count:
    config:
      threshold: 80
  method-lines:
    config:
      threshold: 50
  nested-control-flow:
    config:
      threshold: 4
  return-statements:
    config:
      threshold: 8
  # similar-code:
  #   config:
  #     threshold: 20
  # identical-code:
  #   config:
  #     threshold: 20

exclude_patterns:
  - "tests/"
  - "script/"
  - "docs/"
  - ".*"
  - "**/*.json"
  - "**/*.yml"
  - "**/*.ini"
  - "**/*.txt"
  - "**/*.cfg"
  - "**/*.yaml"
  - "Brew*"
  - "Docker*"
  - "CHANGELOG.md"
  - "CONTRIBUTING.md"
  - "LICENSE"
  - "README.md"
  - "clowder/sitecustomize.py"
  - "setup.py"
