version: "2"

engines:
  pep8:
    enabled: true
  shellcheck:
    enabled: true
  sonar-python:
    enabled: true

ratings:
  paths:
  - "**.py"
  - "**.sh"

checks:
  argument-count:
    config:
      threshold: 5
  complex-logic:
    config:
      threshold: 7
  file-lines:
    config:
      threshold: 1000
  method-complexity:
    config:
      threshold: 7
  method-count:
    config:
      threshold: 30
  method-lines:
    config:
      threshold: 50
