version: "2"

engines:
  pep8:
    enabled: true
  shellcheck:
    enabled: true
  sonar-python:
    enabled: true
  fixme:
    enabled: true
  # TODO: https://docs.codeclimate.com/docs/radon
  # radon:
  #   enabled: true
  # TODO: https://docs.codeclimate.com/docs/bandit
  # bandit:
  #   enabled: true

ratings:
  paths:
  - "**.py"
  - "**.sh"


checks:
  argument-count:
    config:
      threshold: 5
  complex-logic:
    config:
      threshold: 25
  file-lines:
    config:
      threshold: 1000
  method-complexity:
    config:
      threshold: 20
  method-count:
    config:
      threshold: 30
  method-lines:
    config:
      threshold: 50
  nested-control-flow:
    config:
      threshold: 4
  return-statements:
    config:
      threshold: 4
  similar-code:
    config:
      threshold: 10 # language-specific defaults. an override will affect all languages.
  identical-code:
    config:
      threshold: 10 # language-specific defaults. an override will affect all languages.

# exclude_patterns:
#   - "tests/"
#   - "script/"
