coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default: off
      clowder:
        paths:
          - 'clowder'
          - '!clowder/util/clowder.schema.json'
          - '!clowder/util/clowder.config.schema.json'
        target: 70
        threshold: 20
    patch:
       default: off
        #  enabled: no
        #  target: '50'

fixes:
  - "/clowder/::"
  # - "/home/runner/work/clowder/clowder/::"

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment: off
# comment:
#   # layout: "reach,diff,flags,tree"
#   # layout: "files"
#   behavior: default
#   require_changes: no

ignore:
  - ".github/**/*"
  - ".circleci/**/*"
  - ".idea/**/*"
  - ".vscode/**/*"
  - "docs/**/*"
  - "script/**/*"
  - "tests/**/*"
