version: "3.8"
services:
  clowder:
    build: .
    image: clowder:clowder
    stdin_open: true
    tty: true
    entrypoint: /usr/bin/env bash
    cap_add:
      - NET_ADMIN
    volumes:
      - type: bind
        source: .
        target: /clowder
      - ${HOME}/.ssh:/root/.ssh:ro
