version: "3.8"
services:
  clowder:
    build: .
    image: clowder:clowder
    stdin_open: true
    tty: true
    entrypoint: /usr/bin/env bash
    volumes:
      - type: bind
        source: .
        target: /clowder
      - ~/.ssh:/root/.ssh:ro
