version: "3.2"
services:
  clowder:
    container_name: clowder
    build: .
    image: clowder:clowder
    stdin_open: true
    tty: true
    entrypoint: /usr/bin/env bash
    working_dir: ${PWD}
    cap_add:
      - NET_ADMIN
    volumes:
      - type: bind
        source: .
        target: ${PWD}
      - type: bind
        source: /run/host-services/ssh-auth.sock
        target: /run/host-services/ssh-auth.sock
    environment:
      - SSH_AUTH_SOCK=/run/host-services/ssh-auth.sock
