version: 2.1

orbs:
  codecov: codecov/codecov@1.0.2

commands:
  init_code_climate:
    steps:
      - run:
          name: Initialize Code Climate test reporter
          command: |
            script/install_cc_test_reporter
            ./cc-test-reporter before-build
  setup_ssh:
    steps:
      - add_ssh_keys:
          fingerprints:
            - "e9:7d:20:a0:51:b2:9c:22:f6:b9:5b:55:47:c4:7c:20"
      - run:
          name: Add ssh key to known_hosts
          command: ssh-keyscan -H polka-dot-cat.git.beanstalkapp.com >> ~/.ssh/known_hosts
  setup_git_config:
    steps:
      - run:
          name: Setup git config
          command: |
            git config --global user.email "circle@circleci.org"
            git config --global user.name "CircleCI"
            git config --global push.default simple
            git config --global --unset url.ssh://git@github.com.insteadOf
  store_results:
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Generate test reports
          command: script/test report
      - codecov/upload:
          file: build/coverage/coverage.xml
      - run:
          name: Sum coverage for Code climate
          command: |
            ./cc-test-reporter sum-coverage \
              --parts 3 \
              --output build/codeclimate/codeclimate.json \
              build/codeclimate/codeclimate.*.json
      - run:
          name: Upload coverage to Code climate
          command: |
            ./cc-test-reporter upload-coverage \
            --id ${CC_TEST_REPORTER_ID} \
            --input build/codeclimate/codeclimate.json
      - store_test_results:
          path: build/cucumber
      - store_artifacts:
          path: build/cucumber
      - store_artifacts:
          path: build/json
      - store_artifacts:
          path: build/xml
      - store_artifacts:
          path: build/coverage
  test:
    description: "Pytest functional tests"
    parameters:
      modules:
        type: string
      label:
        type: string
      groups:
        type: integer
      group:
        type: integer
    steps:
      - run:
          name: Start clowder tests docker container
          command: script/docker start
      - run: |
          docker-compose exec clowder script/test \
            --modules "<<parameters.modules>>"" \
            --label <<parameters.label>>.<<parameters.group>>
      - run:
          name: Update build files ownership
          command: sudo chown -R ${USER} build
      - run:
          name: Forrmat coverage for Code climate
          command: |
            ./cc-test-reporter format-coverage \
              --input-type coverage.py \
              --output build/codeclimate/codeclimate.<<parameters.label>>.<<parameters.group>>.json \
              build/coverage/coverage.<<parameters.label>>.<<parameters.group>>.xml
      - persist_to_workspace:
          root: .
          paths:
            - build/
  test_parallel:
    description: "Pytest functional tests"
    parameters:
      modules:
        type: string
      label:
        type: string
      groups:
        type: integer
      group:
        type: integer
    steps:
      - run:
          name: Start clowder tests docker container
          command: script/docker start
      - run: |
          docker-compose exec clowder script/test \
            --modules "<<parameters.modules>>"" \
            --label <<parameters.label>>.<<parameters.group>> \
            --parallel
      - run:
          name: Update build files ownership
          command: sudo chown -R ${USER} build
      - run:
          name: Forrmat coverage for Code climate
          command: |
            ./cc-test-reporter format-coverage \
              --input-type coverage.py \
              --output build/codeclimate/codeclimate.<<parameters.label>>.<<parameters.group>>.json \
              build/coverage/coverage.<<parameters.label>>..<<parameters.group>>.xml
      - persist_to_workspace:
          root: .
          paths:
            - build/

jobs:
  test_parallel:
    machine: true
    matrix:
      parameters:
        group: [1, 2, 3, 4]
        groups: 4
    steps:
      - checkout
      - setup_ssh
      - setup_git_config
      - run: pyenv install
      - init_code_climate
      - test_parallel:
          modules: not write and not offline
          label: parallel
          groups: <<matrix.groups>>
          group: <<matrix.group>>
  test_write:
    machine: true
    matrix:
      parameters:
        group: [1, 2, 3, 4]
        groups: 4
    steps:
      - checkout
      - setup_ssh
      - setup_git_config
      - run: pyenv install
      - init_code_climate
      - test:
          modules: write
          label: write
          groups: <<matrix.groups>>
          group: <<matrix.group>>
  test_offline:
    machine: true
    matrix:
      parameters:
        group: [1, 2, 3, 4]
        groups: 4
    steps:
      - checkout
      - setup_ssh
      - setup_git_config
      - run: pyenv install
      - init_code_climate
      - test:
          modules: offline and not write
          label: offline
          groups: <<matrix.groups>>
          group: <<matrix.group>>
  report:
    docker:
      - image: circleci/python:3.7.7
    steps:
      - checkout
      - setup_git_config
      - store_results

workflows:
  pytest:
    jobs:
      - test_parallel
      - test_write
      - test_offline
      - report:
          requires:
            - test_parallel
            - test_write
            - test_offline
