# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.7.7

    working_directory: ~/clowder

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "src/requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            sudo pip3 install -r src/requirements.txt

      - run:
          name: run setup scripts
          command: |
            script/update
            script/test

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "src/requirements.txt" }}

      - run:
          name: setup git config
          command: |
            git config --global user.email "circle@circleci.org"
            git config --global user.name "CircleCI"
            git config --global push.default simple

      - run:
          name: run write tests
          command: clowder-test -c write

      - run:
          name: run misc tests
          command: clowder-test -c misc all

      - run:
          name: upload code coverage results
          command: |
            coverage combine examples/cats examples/llvm-projects examples/swift-projects examples/misc
            aws s3 cp .coverage "s3://clowder-coverage/coverage/circleci/$CIRCLE_BUILD_NUM/"
            codecov -X gcov
