#!/usr/bin/env bash

cd "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/.." || exit 1

./setup
./test

cd "$TRAVIS_BUILD_DIR" || exit 1

if [ "$TRAVIS_OS_NAME" = "osx" ]; then
    PLATFORM='darwin'
elif [ "$TRAVIS_OS_NAME" = "linux" ]; then
    PLATFORM='linux'
fi

# curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-$PLATFORM-amd64 > ./cc-test-reporter
# chmod +x ./cc-test-reporter
# ./cc-test-reporter before-build

setup_git() {
  git config --global user.email "travis@travis-ci.org"
  git config --global user.name "Travis CI"
}
setup_git
