#!/usr/bin/env bash

cd "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/../.." || exit 1

if [ "$TRAVIS_OS_NAME" = "osx" ]; then
    brew link --overwrite python
    pip3 install twine wheel
    pip3 install -r src/requirements.txt
elif [ "$TRAVIS_OS_NAME" = "linux" ]; then
    python3 -m pip install -r src/requirements.txt
fi
