#!/usr/bin/env bash

cd "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/../.." || exit 1

if [ "$PYVERSION" == 'python2' ]; then
    PIP='pip'
else
    PIP='pip3'
fi

if [ "$TRAVIS_OS_NAME" = "osx" ]; then
    brew install github-release
    sudo -H $PIP install twine wheel
fi

sudo $PIP install -r clowder/requirements.txt
