#!/usr/bin/env bash

case "$(uname)" in
    Linux*) export PLATFORM="linux";
        # sudo apt-get update
        # sudo apt-get install python3
        # sudo apt-get upgrade python3
        # sudo apt-get install python3-pip
        # sudo apt-get upgrade python3-pip
        ;;
    Darwin*) export PLATFORM="darwin";
        # brew update
        brew install python3
        brew upgrade python3
        ;;
    CYGWIN*) export PLATFORM="windows";
        ;;
esac

echo " Ran bootstrap script for $PLATFORM"
