#!/usr/bin/env bash

cd "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/.." || exit 1

case "$(uname)" in
    Linux*) export PLATFORM="linux";
        if ! which -s pyenv; then
            curl https://pyenv.run | bash
        fi
        pyenv install || exit 1
        ;;
    Darwin*) export PLATFORM="darwin";
        echo 'Install Hombrew if necessary'
        echo "Checking for homebrew installation"
        if which -s brew; then
            echo "Homebrew already installed! Updating..."
            brew update || exit 1
        else
            echo "Homebrew not found. Installing..."
            ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" || exit 1
        fi
        echo 'Install Homebrew formulas'
        brew bundle || exit 1
        echo 'Install pyenv versions'
        pyenv install || exit 1
        ;;
    CYGWIN*) export PLATFORM="windows";
        echo "Windows is not currently supported"
        exit 1
        ;;
esac

echo " Ran bootstrap script for $PLATFORM"
