#!/usr/bin/env bash

cd "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/.." || exit 1

# case "$(uname)" in
#     Linux*) export PLATFORM="linux";;
#     Darwin*) export PLATFORM="darwin";;
#     CYGWIN*) export PLATFORM="windows";;
# esac

# # Requires CC_TEST_REPORTER_ID is set
# echo 'Download Code Climate test reporter'
# curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-$PLATFORM-amd64 > ./cc-test-reporter
# chmod +x ./cc-test-reporter
# echo 'Initialize Code Climate test reporter'
# ./cc-test-reporter before-build
