#!/usr/bin/env bash

set -euo pipefail
cd "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/.."

# shellcheck disable=SC1091
. 'script/utils.sh'

run script/bootstrap

# h1 'Install pyenv versions'
# run pyenv install --skip-existing

h1 'Install pipenv dependencies'
run pipenv install --dev -e .

h1 'Uninstall system git lfs filters'
sudo git config --system --unset-all filter.lfs.clean || true
sudo git config --system --unset-all filter.lfs.smudge || true
sudo git config --system --unset-all filter.lfs.process || true
sudo git config --system --unset-all filter.lfs.required || true
