#!/usr/bin/env bash
# shellcheck disable=SC1091

set -euo pipefail
cd "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/.."
. 'script/utils.sh'

run "${PWD}/script/setup"

h1 'Uninstall system git lfs filters'
sudo git config --system --unset-all filter.lfs.clean || true
sudo git config --system --unset-all filter.lfs.smudge || true
sudo git config --system --unset-all filter.lfs.process || true
sudo git config --system --unset-all filter.lfs.required || true

h3 'Update pipenv'
run pip install --upgrade pipenv

h3 'Install clowder in editable mode'
run pip install -e .
