#!/usr/bin/env bash

REPO_PATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/.." || exit 1

clean_clowder_repo() {
    echo "Cleaning clowder command files"
    echo "Removing clowder_repo.egg-info"
    local clowder_path=$REPO_PATH
    sudo -H rm -rf $clowder_path/clowder_repo.egg-info
    echo "Removing dist"
    sudo -H rm -rf $clowder_path/dist
    echo "Removing build"
    sudo -H rm -rf $clowder_path/build
    echo "Removing .pyc and __pycache__"
    local path=$clowder_path/clowder
    sudo -H rm -rf $path/*.pyc $path/*/*.pyc $path/*/*/*.pyc
    sudo -H rm -rf $path/__pycache__ $path/*/__pycache__ $path/*/*/__pycache__
    echo "pip3 uninstall clowder"
    pushd $REPO_PATH || exit 1
    sudo -H pip3 uninstall clowder-repo
    popd || exit 1
}
clean_clowder_repo
