#!/usr/bin/env bash

REPO_PATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/.." || exit 1

clean_clowder_repo() {
    echo "Cleaning clowder command files"
    echo "Removing clowder_repo.egg-info"
    local clowder_path=$REPO_PATH
    sudo -H rm -rf $clowder_path/clowder_repo.egg-info
    echo "Removing dist"
    sudo -H rm -rf $clowder_path/dist
    # echo "Removing build"
    # sudo -H rm -rf $clowder_path/build
    echo "Removing __pycache__"
    local path=$clowder_path/clowder
    sudo -H rm -rf $path/__pycache__ $path/*/__pycache__ $path/*/*/__pycache__
    local path=$clowder_path/tests
    sudo -H rm -rf $path/__pycache__ $path/*/__pycache__ $path/*/*/__pycache__
    echo "pip3 uninstall clowder"
    sudo -H pip3 uninstall clowder-repo
}
clean_clowder_repo
