#!/usr/bin/env bash

cd "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/.." || exit 1

start_docker() {
    # Run docker image
    rm -rf build/ssh
    mkdir -p build
    cp -R "${HOME}/.ssh" build/ssh
    docker-compose up --build -d
    docker-compose exec --privileged clowder pip install --requirement requirements.txt
    docker-compose exec --privileged clowder pip install --editable .
    rm -rf build/ssh
}

stop_docker() {
    # Stop running docker container
    docker-compose rm --force --stop clowder
}

if [ "$1" = 'start' ]; then
    start_docker
elif [ "$1" = 'stop' ]; then
    stop_docker
else
    echo 'Requires parameter "start" or "stop"'
fi
