#!/usr/bin/env bash
# shellcheck disable=SC1091

set -euo pipefail
cd "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/.."
. 'script/utils.sh'

DOCS_BUILD_DIR='build/docs'
HTML_DIR="$DOCS_BUILD_DIR/html"

run rm -rf "$DOCS_BUILD_DIR"
run sphinx-apidoc --force --no-toc -d 1 -o docs/rst clowder setup
run sphinx-build docs "$HTML_DIR"

if [ "$1" == 'server' ]; then
    run osascript -e 'tell application "Safari" to open location "127.0.0.1:8000"'
    run sphinx-autobuild docs "$HTML_DIR"
fi
