#!/usr/bin/env bash

cd "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/.." || exit 1

DOCS_BUILD_DIR='build/docs'
HTML_DIR="$DOCS_BUILD_DIR/html"

rm -rf "$DOCS_BUILD_DIR"
sphinx-apidoc --force --no-toc -d 1 -o docs/rst clowder setup
sphinx-build docs "$HTML_DIR"

if [ "$1" == 'server' ]; then
    osascript -e 'tell application "Safari" to open location "127.0.0.1:8000"'
    sphinx-autobuild docs "$HTML_DIR"
fi
