#!/usr/bin/env bash

set -euo pipefail
cd "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/.."

# shellcheck disable=SC1091
. 'script/utils.sh'

if [ -z ${CC_TEST_REPORTER_ID+x} ]; then
    exit_failure 'Requires CC_TEST_REPORTER_ID is set on CI provider'
fi

h1 'Download Code Climate test reporter'
curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-$PLATFORM-amd64 > ./cc-test-reporter
chmod +x ./cc-test-reporter
