#!/usr/bin/env bash

cd "$( dirname "${BASH_SOURCE[0]}" )/.." || exit 1

VERSION=${1:-python2}

if [ -n "$TRAVIS_OS_NAME" ]; then
    if [ -n "$TARGET" ]; then
        if [ "$TARGET" == 'python2' ]; then
            sudo -H pip install -e .
            exit
        fi
    fi
fi

if [ "$VERSION" = 'python2' ]; then
    PIP='pip'
else
    PIP='pip3'
fi

case "$(uname)" in
    Linux*) export MY_PLATFORM="linux";
        sudo -H $PIP install -e .
        ;;
    Darwin*) export MY_PLATFORM="osx";
        sudo -H $PIP install -e .
        ;;
    CYGWIN*) export MY_PLATFORM="windows";
        $PIP install -e .
        ;;
esac

echo $MY_PLATFORM
