#!/usr/bin/env bash

if [ -z "$1" ]; then
    echo 'Requires parameter "cocos2d", "cats", "llvm", "swift", "offline", or "all"'
    exit 1
fi

ACCESS_LEVEL=${2:-read}

cd "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )" || exit 1

./update

if [ $1 == "cats" ]; then
    ./tests/test_example_cats.sh $ACCESS_LEVEL || exit 1
elif [ $1 == "cocos2d" ]; then
    ./tests/test_example_cocos2d.sh || exit 1
elif [ $1 == "llvm" ]; then
    ./tests/test_example_llvm.sh $ACCESS_LEVEL || exit 1
elif [ $1 == "swift" ]; then
    ./tests/test_example_swift.sh $ACCESS_LEVEL || exit 1
elif [ $1 == "offline" ]; then
    ./tests/test_cats_offline.sh || exit 1
elif [ $1 == "all" ]; then
    ./tests/test_example_cats.sh $ACCESS_LEVEL || exit 1
    ./tests/test_example_llvm.sh $ACCESS_LEVEL || exit 1
    ./tests/test_example_swift.sh $ACCESS_LEVEL || exit 1
    ./tests/test_cats_offline.sh || exit 1
else
    echo 'Requires parameter "cocos2d", "cats", "llvm", "swift", "offline", or "all"'
    exit 1
fi
