#!/usr/bin/env bash

cd "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )" || exit 1

if [ "$1" == 'version' ]; then
    cd ..
    OLD_VERSION=$(awk "/version='/" src/setup.py | sed -n -e "s/^.*version='//p" | tr -d "',")
    NEW_VERSION=$2

    perl -pi -e "s/$OLD_VERSION/$NEW_VERSION/g" src/setup.py || exit 1
    perl -pi -e "s/$OLD_VERSION/$NEW_VERSION/g" .github/issue_template.md || exit 1
    perl -pi -e "s/$OLD_VERSION/$NEW_VERSION/g" docs/conf.py || exit 1
    exit
fi

if [ "$1" == 'website' ]; then
    cd ..
    GH_PAGES_DIR="$( cd .. && pwd)/clowder-gh-pages"
    rm -rf $GH_PAGES_DIR || exit 1
    git clone git@github.com:JrGoodle/clowder.git -b gh-pages $GH_PAGES_DIR || exit 1

    script/process_readme.py || exit 1

    INDEX_FILE="$GH_PAGES_DIR/index.md"
    rm -f "$INDEX_FILE" || exit 1
    mv 'README-processed.md' "$INDEX_FILE" || exit 1

    # cd $GH_PAGES_DIR || exit 1
    # git add index.md docs/README || exit 1
    # git commit -m 'Update web site from latest in master branch' || exit 1
    # git push || exit 1
    exit
fi

if [ "$1" == 'docs' ]; then
    cd ..
    rm docs/clowder.rst
    rm docs/clowder.*.rst
    sphinx-apidoc -o docs src
    rm docs/modules.rst
    rm docs/setup.rst
    exit
fi

if [ "$1" == 'schema' ]; then
    cd ..
    # TODO: Separate json schema descriptions into separate file
    # Add script to generate local
    exit
fi

./clean 'clowder' || exit 1

pushd '../src' || exit 1

case "$(uname)" in
    Linux*) export PLATFORM="linux";
        pip install -r requirements.txt || exit 1
        ;;
    Darwin*) export PLATFORM="darwin";
        sudo -H pip install -r requirements.txt || exit 1
        ;;
    CYGWIN*) export PLATFORM="windows";
        pip install -r requirements.txt || exit 1
        ;;
esac

echo "Installed clowder for $PLATFORM"
