#!/usr/bin/env bash
# shellcheck disable=SC1091

set -euo pipefail
cd "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/.."
. 'script/utils.sh'

run "${PWD}/script/setup"

. script/import.sh
. script/import_python.sh

h3 'Install clowder in editable mode'
run pipenv run pip install -e .

h1 'Generate requirements.txt'
run 'pipenv run pip freeze > requirements.txt'
