#!/usr/bin/env bash

cd "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )" || exit 1

if [ "$1" == 'version' ]; then
    cd ..
    OLD_VERSION=$(awk "/version='/" setup.py | sed -n -e "s/^.*version='//p" | tr -d "',")
    NEW_VERSION=$2

    perl -pi -e "s/$OLD_VERSION/$NEW_VERSION/g" README.md || exit 1
    perl -pi -e "s/$OLD_VERSION/$NEW_VERSION/g" setup.py || exit 1
    perl -pi -e "s/$OLD_VERSION/$NEW_VERSION/g" clowder/cmd.py || exit 1
    exit
fi

if [ "$1" == 'website' ]; then
    cd ..
    GH_PAGES_DIR="$( cd .. && pwd)/clowder-gh-pages"
    rm -rf $GH_PAGES_DIR || exit 1
    git clone git@github.com:JrGoodle/clowder.git -b gh-pages $GH_PAGES_DIR || exit 1

    tail -n+3 "README.md" > "$GH_PAGES_DIR/index.md" || exit 1
    rm -rf "$GH_PAGES_DIR/docs/README" || exit 1
    cp -R 'docs/README' "$GH_PAGES_DIR/docs/README" || exit 1

    cd $GH_PAGES_DIR || exit 1
    git add index.md docs/README || exit 1
    git commit -m 'Update web site from latest in master branch' || exit 1
    git push || exit 1
    exit
fi

VERSION=${1:-python3}

echo "pip uninstall clowder"
sudo -H pip2 uninstall clowder-repo
sudo -H pip3 uninstall clowder-repo

./clean
./setup $VERSION
