#!/usr/bin/env bash
# shellcheck disable=SC1091

set -euo pipefail
cd "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/.."
source "script/utils.sh"

GH_PAGES_DIR="$( cd .. && pwd)/clowder-gh-pages"
run rm -rf "$GH_PAGES_DIR"
run git clone git@github.com:JrGoodle/clowder.git -b gh-pages "$GH_PAGES_DIR"

run script/process_readme.py

INDEX_FILE="$GH_PAGES_DIR/index.md"
run rm -f "$INDEX_FILE"
run mv 'README-processed.md' "$INDEX_FILE"

# pushd "$GH_PAGES_DIR"
# run git add index.md docs/README
# run git commit -m 'Update web site from latest in master branch'
# run git push
