#!/usr/bin/env bash

cd "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/.." || exit 1

GH_PAGES_DIR="$( cd .. && pwd)/clowder-gh-pages"
rm -rf $GH_PAGES_DIR || exit 1
git clone git@github.com:JrGoodle/clowder.git -b gh-pages $GH_PAGES_DIR || exit 1

script/process_readme.py || exit 1

INDEX_FILE="$GH_PAGES_DIR/index.md"
rm -f "$INDEX_FILE" || exit 1
mv 'README-processed.md' "$INDEX_FILE" || exit 1

# cd $GH_PAGES_DIR || exit 1
# git add index.md docs/README || exit 1
# git commit -m 'Update web site from latest in master branch' || exit 1
# git push || exit 1
