name: 'CI - cats lfs'

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'docs/**'
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'docs/**'

defaults:
  run:
    shell: bash

jobs:
  cats_lfs:
    env:
      PYTHON_VERSION: ${{ matrix.python-version }}
      OS_NAME: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest] # TODO: windows-latest
        python-version: ['3.6', '3.7', '3.8']
        exclude:
          - os: macos-latest
            python-version: '3.6'
          - os: macos-latest
            python-version: '3.8'
    steps:
    - uses: actions/checkout@v2
    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Setup git config
      run:
        git config --global user.email "joe@polka.cat";
        git config --global user.name "GitHub Actions Workflow"
    - name: Install clowder requirements
      run: pip3 install -r src/requirements.txt
    - name: CI before script
      run: script/ci_before
    - name: Install clowder
      run: script/update
    - name: Install clowder test
      run: script/test
    - name: Test lfs commands
      run: clowder-test -c cats lfs
    - name: CI after script
      run: script/ci_after
