name: 'CI - pytest'

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'docs/**'
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'docs/**'

defaults:
  run:
    shell: bash

jobs:
  pytest:
    env:
      PYTHON_VERSION: ${{ matrix.python-version }}
      OS_NAME: ${{ matrix.os }}
      CLOWDER_DEBUG: true
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest] # TODO: windows-latest
        python-version: ['3.6', '3.7', '3.8']
    steps:
    - uses: actions/checkout@v2
    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Setup git config
      run:
        git config --global user.email "joe@polka.cat";
        git config --global user.name "GitHub Actions Workflow"
    - name: Install clowder
      run: script/update
    - name: Run pytest functional tests
      run: pytest --cov-config=.coveragerc --basetemp=build --cov-append --cov=clowder -vv -n auto -m "not ssh and not config and not write and not offline"
    - name: Run pytest config tests
      run: pytest --cov-config=.coveragerc --basetemp=build --cov-append --cov=clowder -vv -m "config and not ssh and not write and not offline"
    - uses: codecov/codecov-action@v1
      with:
        file: coverage/.coverage
