name: 'CI - pytest'

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'docs/**'
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'docs/**'

defaults:
  run:
    shell: bash

jobs:
  pytest:
    env:
      PYTHON_VERSION: ${{ matrix.python-version }}
      OS_NAME: ${{ matrix.os }}
      CLOWDER_DEBUG: true
      PYTHONPATH: ${{ github.workspace }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [
          macos-latest,
          ubuntu-latest,
          # TODO: windows-latest
        ]
        python-version: [
          '3.8',
          '3.9',
          '3.10',
          '3.11'
        ]
    steps:
    - uses: actions/checkout@v3
    - name: Setup python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Setup git config
      run: |
        git config --global user.email "joe@polka.cat";
        git config --global user.name "GitHub Actions Workflow"
    # - if: runner.os == 'macOS'
    #   name: Print PATH
    #   run: |
    #     echo $PATH
    # - if: runner.os == 'macOS'
    #   name: Fix Python PATH on macOS
    #   run: |
    #     tee -a ~/.profile <<<'export PATH="$pythonLocation:$PATH:$pythonLocation"'
    - if: runner.os == 'macOS'
      name: Print PATH
      run: |
        export PATH="$pythonLocation:$PATH:$pythonLocation"
        echo $PATH
    - name: Install clowder
      run: |
        export PATH="$pythonLocation:$PATH:$pythonLocation"
        script/cibuild
    - name: Run pytest functional tests
      run: |
        export PATH="$pythonLocation:$PATH:$pythonLocation"
        script/test \
          --markers 'not ssh and not offline' \
          --parallel \
          --exitfirst
    - uses: actions/upload-artifact@v2
      with:
        name: coverage-ghworkflow-${{ matrix.os }}-${{ matrix.python-version }}
        path: |
          build/cucumber
          build/junit
          build/coverage
    - uses: deblockt/cucumber-report-annotations-action@v1.6
      with:
        access-token: ${{ secrets.GITHUB_TOKEN }}
        path: build/cucumber/results.json
    - uses: ashley-taylor/junit-report-annotations-action@1.3
      if: always()
      with:
        access-token: ${{ secrets.GITHUB_TOKEN }}
        path: build/junit/results.xml
