name: Deploy GitHub Pages website

on:
  push:
    branches:
      - master
    paths:
      - README.md

defaults:
  run:
    shell: bash

jobs:
  cats_branch:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    # - name: Deploy GitHub Pages website
    #   run: script/update website
