name: 'Deploy'

on:
  push:
    branches:
      - master

defaults:
  run:
    shell: bash

jobs:
  cats_branch:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
    - name: Setup git config
      run:
        git config --global user.email "joe@polka.cat";
        git config --global user.name "GitHub Actions Workflow"
    - name: Install homebrew dependencies
      run: brew install github-release
    - name: Install clowder requirements
      run: pip3 install -r requirements.txt
    - name: Install clowder
      run: script/update
    - name: Install clowder test
      run: script/test
    # - name: Deploy script
    #   run: script/deploy
